import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
// import CustomCursor from "./components/CustomCursor";

const inter = Inter({ subsets: ["latin"] });

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Deadwell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${merriweather.variable}`}>{children}</body>
    </html>
  );
}

// to add new fonts to the project, follow this guide: https://medium.com/@dolce-emmy/integrating-multiple-google-fonts-in-a-next-js-14-project-a-step-by-step-guide-ef051f3264e1

// 1- import the font here (layouts.tsx) and create a const 
// 2- add the variable in globals.css
// 3- use it in classnames with tailwind